# Generated by Django 4.2.19 on 2025-02-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1_3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='charge',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
