# Generated by Django 4.2.19 on 2025-02-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1_3', '0002_alter_charge_created_at_alter_charge_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='id',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
