# Generated by Django 4.2.19 on 2025-02-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_prueba_tecnica',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('company_id', models.CharField(max_length=40, null=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.CharField(max_length=255)),
                ('paid_at', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
